//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AuthorsBooks
    {
        [Key]
        public int AuthorBookID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> BookID { get; set; }

        [ForeignKey("AuthorID")]
        public virtual Authors Authors { get; set; }
        [ForeignKey("BookID")]
        public virtual Books Books { get; set; }
    }
}
