//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksCategories
    {
        public int BookCategoryID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
