//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBEntities : DbContext
    {
        public LibraryDBEntities()
            : base("name=LibraryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<AuthorsBooks> AuthorsBooks { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BooksCategories> BooksCategories { get; set; }
        public virtual DbSet<BooksPublishers> BooksPublishers { get; set; }
        public virtual DbSet<BooksUsers> BooksUsers { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<LibraryUsers> LibraryUsers { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }

    }
}
